spring.application.name=eduqa-backend
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/eduqa
spring.datasource.password=postgres
# spring.datasource.password=0789020199
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000
spring.mail.host=smtp.gmail.com
# spring.mail.password=
# spring.mail.username=
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
